

export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4,
    imageUrl: 'assets/images/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'assets/images/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 4,
    imageUrl: 'assets/images/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'assets/images/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3,
    imageUrl: 'assets/images/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4,
    imageUrl: 'assets/images/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: 'Margherita Pizza',
    price: 10,
    cookTime: '50-60',
    favorite: true,
    origins: ['italy'],
    stars: 4,
    imageUrl: 'assets/images/food-7.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '8',
    name: 'Chicken Burger',
    price: 5,
    cookTime: '10-15',
    favorite: true,
    origins: ['usa'],
    stars: 4.5,
    imageUrl: 'assets/images/food-8.jpg',
    tags: ['FastFood', 'Burger', 'Dinner'],
  },
  {
    id: '9',
    name: 'Pasta Carbonara',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['italy'],
    stars: 4.2,
    imageUrl: 'assets/images/food-9.jpg',
    tags: ['SlowFood', 'Pasta', 'Lunch'],
  },
  {
    id: '10',
    name: 'Tomato Soup',
    price: 7,
    cookTime: '15-20',
    favorite: false,
    origins: ['france'],
    stars: 4.0,
    imageUrl: 'assets/images/food-10.jpg',
    tags: ['Soup', 'Lunch'],
  },
];

export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "John@123",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "Jane@123",
    address: "Shanghai",
    isAdmin: false,
  },
];